/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Custom thresholds for network errors detection. If not present (null) then default thresholds will be used.
type NetworkErrorsThresholds struct {
	// Detect high network errors number only when receive/transmit error packet percentage is higher than N percent in 3 out of 5 samples.
	ErrorsPercentage int32 `json:"errorsPercentage"`
	// Detect high network errors number only when receive/transmit total packets rate is higher than N packets/s in 3 out of 5 samples.
	TotalPacketsRate int32 `json:"totalPacketsRate"`
}
