/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type RequestAttributeStub struct {
	// The ID of the request attribute.
	Id string `json:"id,omitempty"`
	// The name of the request attribute.
	Name string `json:"name,omitempty"`
}
