/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type ConfigurationHistory struct {
	Metadata ConfigurationHistoryMetadata `json:"metadata,omitempty"`
	// Start timestamp of the report timeframe, in UTC milliseconds.
	From int64 `json:"from,omitempty"`
	// End timestamp of the report timeframe, in UTC milliseconds.
	To int64 `json:"to,omitempty"`
	// If true, the queried timespan contained more results than could be delivered at once so only the most recent results were delivered, older ones truncated.
	ResultsTruncated bool `json:"resultsTruncated,omitempty"`
	// List of all configuration changes during the specified timeframe.
	Results []ConfigurationInstanceDto `json:"results,omitempty"`
	// If the result limit was exceeded, the timestamp of the first result that was truncated. Use this as your query's \"to\" to get the next batch of results.
	TimestampOfFirstTruncatedResult int64 `json:"timestampOfFirstTruncatedResult,omitempty"`
}
