/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Custom thresholds for undersized storage device detection. If not present (null) then default thresholds will be used.
type UndersizedStorageThresholds struct {
	// Detect undersized storage device always when average queue command latency is higher than N milliseconds in 3 out of 5 samples.
	AverageQueueCommandLatency int32 `json:"averageQueueCommandLatency"`
	// Detect undersized storage device always when peak queue command latency is higher than N milliseconds in 3 out of 5 samples.
	PeakQueueCommandLatency int32 `json:"peakQueueCommandLatency"`
}
