/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type ScopeConditions struct {
	// Only applies to this service technology.
	ServiceTechnology string `json:"serviceTechnology,omitempty"`
	// Only applies to this process group. Note that this can't be transferred between different clusters or environments.
	ProcessGroup string `json:"processGroup,omitempty"`
	// Only apply to process groups matching this tag.
	TagOfProcessGroup string `json:"tagOfProcessGroup,omitempty"`
}
