/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Settings for the Waterfall analysis.
type WaterfallSettings struct {
	// Threshold for warning about uncompressed resources that are larger than x bytes.
	UncompressedResourcesThreshold int32 `json:"uncompressedResourcesThreshold"`
	// Threshold for warning about resources that are larger than x bytes.
	ResourcesThreshold int32 `json:"resourcesThreshold"`
	// Threshold for warning about resources with a lower browser cache rate than x%.
	ResourceBrowserCachingThreshold int32 `json:"resourceBrowserCachingThreshold"`
	// Threshold for warning about slow first party resources that have a response time larger than x micro seconds.
	SlowFirstPartyResourcesThreshold int32 `json:"slowFirstPartyResourcesThreshold"`
	// Threshold for warning about slow third party resources that have a response time larger than x micro seconds.
	SlowThirdPartyResourcesThreshold int32 `json:"slowThirdPartyResourcesThreshold"`
	// Threshold for warning about slow CDN resources that have a response time larger than x micro seconds.
	SlowCdnResourcesThreshold int32 `json:"slowCdnResourcesThreshold"`
}
