/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type ApplicationDataPrivacyListDto struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	Values []ApplicationDataPrivacy `json:"values,omitempty"`
}
