/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Custom thresholds for low disk inodes number detection. If not present (null) then default thresholds will be used.
type DiskLowInodesThresholds struct {
	// Detect low disk inodes when if percent of available inodes is lower than N percent in 3 out of 5 samples.
	FreeInodesPercentage int32 `json:"freeInodesPercentage"`
}
