/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Custom thresholds for high retransmission rate detection. If not present (null) then default thresholds will be used.
type NetworkHighRetransmissionThresholds struct {
	// Detect high retransmission only when retransmission rate is higher than N percent.
	RetransmissionRatePercentage int32 `json:"retransmissionRatePercentage"`
	// Detect high retransmission only when number of retransmitted packets is higher than N packets/min in 3 out of 5 samples.
	RetransmittedPacketsNumberPerMinute int32 `json:"retransmittedPacketsNumberPerMinute"`
}
