/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type SimpleTech struct {
	// Predefined technology, if technology is not predefined, then the verbatim type must be set
	Type string `json:"type,omitempty"`
	// Non-predefined technology, use for custom technologies.
	VerbatimType string `json:"verbatimType,omitempty"`
}
