/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Configuration for an auto tag. This config contains information when the tag should be automatically assigned to entities.
type AutoTag struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// The ID of the rule-based tag.
	Id string `json:"id,omitempty"`
	// The name of the rule-based tag. This is the actual tag value which is associated with entities.If a 'valueFormat' is defined inside a rule, the name of this tag will represent the tag key for this rule.
	Name string `json:"name"`
	// The list of rules when to associate this tag with an entity. Each rule is evaluated independently of all other rules.
	Rules []AutoTagRule `json:"rules,omitempty"`
}
