/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Custom thresholds for slow disk writes and reads detection. If not present (null) then default thresholds will be used.
type DiskLowSpaceThresholds struct {
	// Detect slow disk writes and reads when ead time and write time is higher than N milliseconds.
	WriteAndReadTime int32 `json:"writeAndReadTime"`
}
