/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Metadata useful for debugging
type ConfigurationHistoryMetadata struct {
	// The type of configuration.
	Type string `json:"type,omitempty"`
	// Dynatrace server version.
	ClusterVersion string `json:"clusterVersion,omitempty"`
}
