/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Settings regarding global event capturing.
type GlobalEventCaptureSettings struct {
	// MouseUp enabled/disabled.
	MouseUp bool `json:"mouseUp"`
	// MouseDown enabled/disabled.
	MouseDown bool `json:"mouseDown"`
	// Click enabled/disabled.
	Click bool `json:"click"`
	// DoubleClick enabled/disabled.
	DoubleClick bool `json:"doubleClick"`
	// KeyUp enabled/disabled.
	KeyUp bool `json:"keyUp"`
	// KeyDown enabled/disabled.
	KeyDown bool `json:"keyDown"`
	// Scroll enabled/disabled.
	Scroll bool `json:"scroll"`
	// Additional events to be captured globally as user input.
	AdditionalEventCapturedAsUserInput string `json:"additionalEventCapturedAsUserInput"`
}
