/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Configuration of lost connection detection
type ConnectionLostDetectionConfig struct {
	// Is detection enabled.
	Enabled bool `json:"enabled"`
	// Is detection enabled during graceful host shutdowns.
	EnabledOnGracefulShutdowns bool `json:"enabledOnGracefulShutdowns"`
}
