/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Management Zone stub - only contains id and name of a management zone.
type ManagementZoneStub struct {
	// The id of the management zone.
	Id string `json:"id,omitempty"`
	// The name of the management zone.
	Name string `json:"name,omitempty"`
}
