/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Custom thresholds for high number of dropped packets detection. If not present (null) then default thresholds will be used.
type DroppedPacketsThresholds struct {
	// Detect high number of dropped packets when receive/transmit dropped packets rate on NIC is higher than N per second in 3 out of 20 samples.
	DroppedPacketsPerSecond int32 `json:"droppedPacketsPerSecond"`
}
