/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type EntityRuleEngineDynamicCustomHostMetadataConditionKey struct {
	// Defines the attribute used for the filter. Only some are allowed based on the feature it is used for and the specified 'type' outside this condition.
	Attribute string `json:"attribute"`
	Type string `json:"type,omitempty"`
	DynamicKey CustomHostMetadataKey `json:"dynamicKey"`
}
