/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// List of auto tag stubs
type AutoTagStubList struct {
	// Configured rule based tag stubs
	Values []AutoTagStub `json:"values,omitempty"`
}
