/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// List of management zone stubs
type ManagementZoneStubList struct {
	// Configured management zone stubs
	Values []ManagementZoneStub `json:"values,omitempty"`
}
