/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


type WebApplicationConfigStub struct {
	// The unique id of the web application, automatically generated by the dynatrace server.
	Identifier string `json:"identifier,omitempty"`
	// The name of the Web Application
	Name string `json:"name,omitempty"`
}
