/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf


// Response time degradation detection configuration.
type ResponseTimeDegradationDetectionConfig struct {
	// How to detect response time degradation: automatically, based on fixed thresholds, or do not detect.
	DetectionMode string `json:"detectionMode"`
	AutomaticDetection ResponseTimeDegradationAutodetectionConfig `json:"automaticDetection,omitempty"`
	Thresholds ResponseTimeDegradationThresholdConfig `json:"thresholds,omitempty"`
}
