/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapiconf

// JavaScript framework support.
type JavaScriptFrameworkSupport struct {
	// Support for AngularJS and Angular JavaScript frameworks enabled/disabled
	Angular bool `json:"angular"`
	// Support for Dojo JavaScript framework enabled/disabled
	Dojo bool `json:"dojo"`
	// Support for ExtJS, Sencha Touch JavaScript frameworks enabled/disabled
	ExtJS bool `json:"extJS"`
	// Support for ICEfaces JavaScript framework enabled/disabled
	Icefaces bool `json:"icefaces"`
	// Support for jQuery, Backbone.js JavaScript frameworks enabled/disabled
	JQuery bool `json:"jQuery"`
	// Support for MooTools JavaScript framework enabled/disabled
	MooTools bool `json:"mooTools"`
	// Support for Prototype JavaScript framework enabled/disabled
	Prototype bool `json:"prototype"`
	// Support for ActiveXObject detection JavaScript framework enabled/disabled
	ActiveXObject bool `json:"activeXObject"`
}
