/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


// Synthetic test step.
type SyntheticTestStep struct {
	// Unique ID of the step.
	Id int64 `json:"id,omitempty"`
	// Step name, displayed in the UI.
	Title string `json:"title,omitempty"`
}
