/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


// Operation state to be set for all external Synthetic monitors
type StateModification struct {
	// The new operation state for all external Synthetic monitors.
	State string `json:"state"`
}
