/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


type ExternalSyntheticTests struct {
	// Synthetic engine name.
	SyntheticEngineName string `json:"syntheticEngineName,omitempty"`
	// Synthetic engine icon URL.
	SyntheticEngineIconUrl string `json:"syntheticEngineIconUrl,omitempty"`
	// Message creation timestamp, UTC milliseconds.
	MessageTimestamp int64 `json:"messageTimestamp"`
	// Test sites definition.
	Locations []SyntheticLocation `json:"locations,omitempty"`
	// Set of external Synthetic tests.
	Tests []ExternalSyntheticTest `json:"tests,omitempty"`
	// Set of external Synthetic test results.
	TestResults []ExternalSyntheticTestResult `json:"testResults,omitempty"`
}
