/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


// Defines the version of the agent currently running on the entity.
type AgentVersion struct {
	// The major version number.
	Major int32 `json:"major,omitempty"`
	// The minor version number.
	Minor int32 `json:"minor,omitempty"`
	// The revision number.
	Revision int32 `json:"revision,omitempty"`
	// A string representation of the SVN revision number.
	SourceRevision string `json:"sourceRevision,omitempty"`
	// A timestamp string: format \"yyyymmdd-hhmmss
	Timestamp string `json:"timestamp,omitempty"`
}
