/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


// Single Event that is returned in the Event Feed Query
type EventRestEntry struct {
	// Timestamp when the event was detected
	StartTime int64 `json:"startTime,omitempty"`
	// Timestamp when the event was closed
	EndTime int64 `json:"endTime,omitempty"`
	// The ID of the affected Dynatrace entity.    You can find the ID in the URL of the corresponding Dynatrace entity page, for example, `HOST-007`.
	EntityId string `json:"entityId,omitempty"`
	// The name of the affected Dynatrace entity.
	EntityName string `json:"entityName,omitempty"`
	// The severity of the event.
	SeverityLevel string `json:"severityLevel,omitempty"`
	// The impact level of the event.
	ImpactLevel string `json:"impactLevel,omitempty"`
	// The type of the event.
	EventType string `json:"eventType,omitempty"`
	// Specifies the event state
	EventStatus string `json:"eventStatus,omitempty"`
	// Collects all the tags associated with the monitored entity that raises the event
	Tags []TagInfo `json:"tags,omitempty"`
	// Encoded Event identifier
	Id string `json:"id,omitempty"`
}
