/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


// Object defining recurrence of the maintenance window.
type MaintenanceWindowRecurrence struct {
	// The day of the week for weekly maintenance.    The format is the full name of the day in upper case, for example `WEDNESDAY`.
	Day string `json:"day,omitempty"`
	// The day of the month for monthly maintenance.
	DayOfMonth int32 `json:"dayOfMonth,omitempty"`
	// Time of the maintenance window start. The format is `HH:mm`.
	Start string `json:"start"`
	// Duration of the maintenance window in minutes.
	Duration int32 `json:"duration"`
}
