/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dtapienv


// Synthetic test location.
type SyntheticTestLocation struct {
	// Unique ID of the location.
	Id string `json:"id"`
	// Location enabled/disabled. Default is `true`.
	Enabled bool `json:"enabled,omitempty"`
}
