/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// The properties of an event.
type Event struct {
	// Timestamp of the event detection, in UTC milliseconds.
	StartTime int64 `json:"startTime,omitempty"`
	// Timestamp of the event closure, in UTC milliseconds.  `-1` if the event is still open.
	EndTime int64 `json:"endTime,omitempty"`
	// The ID of the affected Dynatrace entity.    You can find the ID in the URL of the corresponding Dynatrace entity page, for example, `HOST-007`.
	EntityId string `json:"entityId,omitempty"`
	// The name of the affected Dynatrace entity.
	EntityName string `json:"entityName,omitempty"`
	// The severity of the event.
	SeverityLevel string `json:"severityLevel,omitempty"`
	// The impact level of the event.
	ImpactLevel string `json:"impactLevel,omitempty"`
	// The type of the event.
	EventType string `json:"eventType,omitempty"`
	// The status of the event.
	Status string `json:"status,omitempty"`
	// Additional data on the event severity.
	Severities []EventSeverity `json:"severities,omitempty"`
	// Whether the event is the root cause of the problem.
	IsRootCause bool `json:"isRootCause,omitempty"`
	// 
	DeploymentProject string `json:"deploymentProject,omitempty"`
	// 
	CpuLimitInMHz int32 `json:"cpuLimitInMHz,omitempty"`
	// 
	DeploymentParamAdded string `json:"deploymentParamAdded,omitempty"`
	// For events with the event type 'MONITORING_UNAVAILABLE' it may occur that the event is occurring on the entire Dynatrace cluster. If this is true it could be that there are problems on Dynatrace' side.
	IsClusterWide bool `json:"isClusterWide,omitempty"`
	// 
	Source string `json:"source,omitempty"`
	// 
	EffectiveEntity string `json:"effectiveEntity,omitempty"`
	// 
	OperatingSystem string `json:"operatingSystem,omitempty"`
	// 
	Artifact string `json:"artifact,omitempty"`
	// 
	CpuLoad float32 `json:"cpuLoad,omitempty"`
	// 
	AffectedRequestsPerMinute float32 `json:"affectedRequestsPerMinute,omitempty"`
	// 
	AnnotationDescription string `json:"annotationDescription,omitempty"`
	// 
	Browser string `json:"browser,omitempty"`
	// 
	AffectedSyntheticLocations []string `json:"affectedSyntheticLocations,omitempty"`
	// 
	DeploymentName string `json:"deploymentName,omitempty"`
	// 
	DeploymentParamRemoved string `json:"deploymentParamRemoved,omitempty"`
	// 
	UserDefined50thPercentileThreshold float32 `json:"userDefined50thPercentileThreshold,omitempty"`
	// 
	ServiceMethodGroup string `json:"serviceMethodGroup,omitempty"`
	// 
	ReferenceResponseTime90thPercentile float32 `json:"referenceResponseTime90thPercentile,omitempty"`
	// 
	UserAction string `json:"userAction,omitempty"`
	// 
	MinimumProcessGroupInstanceCountThreshold int32 `json:"minimumProcessGroupInstanceCountThreshold,omitempty"`
	// 
	ReferenceResponseTime50thPercentile float32 `json:"referenceResponseTime50thPercentile,omitempty"`
	// 
	UserDefined90thPercentileThreshold float32 `json:"userDefined90thPercentileThreshold,omitempty"`
	// 
	DeploymentVersion string `json:"deploymentVersion,omitempty"`
	// 
	AnnotationType string `json:"annotationType,omitempty"`
	// If the event type is one of the synthetic event types then we may have information which synthetic actions are affected by the event. The names of those are returned in this field.
	AffectedSyntheticActions []string `json:"affectedSyntheticActions,omitempty"`
	// 
	AffectedUserActionsPerMinute float32 `json:"affectedUserActionsPerMinute,omitempty"`
	// 
	ActiveMaintenanceWindows []string `json:"activeMaintenanceWindows,omitempty"`
	// 
	MobileAppVersion string `json:"mobileAppVersion,omitempty"`
	// 
	UserDefinedFailureRateThreshold float32 `json:"userDefinedFailureRateThreshold,omitempty"`
	// 
	Percentile string `json:"percentile,omitempty"`
	// 
	CustomProperties map[string]string `json:"customProperties,omitempty"`
	// 
	RemediationAction string `json:"remediationAction,omitempty"`
	// 
	Service string `json:"service,omitempty"`
	// 
	CiBackLink string `json:"ciBackLink,omitempty"`
	// 
	Geolocation string `json:"geolocation,omitempty"`
	// 
	ServiceMethod string `json:"serviceMethod,omitempty"`
}
