/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Tag of a Dynatrace entity.
type TagInfo struct {
	// The origin of the tag, like AWS or Cloud Foundry.   Custom tags use the `CONTEXTLESS` value.
	Context string `json:"context,omitempty"`
	// The key of the tag.   Custom tags have the tag value here.
	Key string `json:"key"`
	// The value of the tag.   Not applicable to custom tags.
	Value string `json:"value,omitempty"`
}
