/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


type SyntheticTestLocation struct {
	// Unique id which identifies the location.
	Id string `json:"id"`
	// True if enabled, false if disabled or deleted, defaults to true.
	Enabled bool `json:"enabled,omitempty"`
}
