/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Information about one Synthetic Tests
type ExternalSyntheticTest struct {
	// Unique id which identifies the test.
	Id string `json:"id"`
	// Test title.
	Title string `json:"title,omitempty"`
	// Test description.
	Description string `json:"description,omitempty"`
	// Test setup information.
	TestSetup string `json:"testSetup,omitempty"`
	// Date as timestamp in millis UTC Dynatrace Cluster Time when this test automatically expires.
	ExpirationTimestamp int64 `json:"expirationTimestamp,omitempty"`
	// An URL to link to this test results.
	DrilldownLink string `json:"drilldownLink,omitempty"`
	// Link back to where the user can edit that test in the original UI.
	EditLink string `json:"editLink,omitempty"`
	// Enabled state. Defaults to true.
	Enabled bool `json:"enabled,omitempty"`
	// Deletion state of a test. Additionally set enabled to false if this field is set to true. Defaults to false.
	Deleted bool `json:"deleted,omitempty"`
	// One or more locations where this test runs.
	Locations []SyntheticTestLocation `json:"locations,omitempty"`
	// One or more steps with their metainfo within a synthetic test.
	Steps []SyntheticTestStep `json:"steps,omitempty"`
	// Timeout in milliseconds - after this time has passed and no result has been sent for this test we will switch the availability state to unmonitored. Defaults to 2 * scheduleIntervalInSec.
	NoDataTimeout int32 `json:"noDataTimeout,omitempty"`
	// Schedule in seconds.
	ScheduleIntervalInSeconds int32 `json:"scheduleIntervalInSeconds"`
}
