/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


type EventPushMessage struct {
	// The predefined event type
	EventType string `json:"eventType,omitempty"`
	// Optional start timestamp of the event in UTC milliseconds (for example 1495200637630). The actual time is used for the event if no start timestamp is provided.
	Start int64 `json:"start,omitempty"`
	// Optional end timestamp of the event in UTC milliseconds. The actual time is used if no end timestamp is provided.
	End int64 `json:"end,omitempty"`
	AttachRules PushEventAttachRules `json:"attachRules,omitempty"`
	// Dictionary of custom key value pairs that can be used to send additional information along with the event
	CustomProperties map[string]map[string]interface{} `json:"customProperties,omitempty"`
}
