/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


type TechnologyInfo struct {
	Type string `json:"type,omitempty"`
	Edition string `json:"edition,omitempty"`
	Version string `json:"version,omitempty"`
}
