/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// The properties of a problem.
type Problem struct {
	// The ID of the problem.
	Id string `json:"id,omitempty"`
	// Timestamp of the problem start, in UTC milliseconds.
	StartTime int64 `json:"startTime,omitempty"`
	// Timestamp of the problem end, in UTC milliseconds. `-1` if the problem is still open.
	EndTime int64 `json:"endTime,omitempty"`
	// The name of the problem, displayed in the UI.
	DisplayName string `json:"displayName,omitempty"`
	// The impact level of the problem. It shows what is affected by the problem: infrastructure, service, or application.
	ImpactLevel string `json:"impactLevel,omitempty"`
	// The status of the problem.
	Status string `json:"status,omitempty"`
	// The severity of the problem.
	SeverityLevel string `json:"severityLevel,omitempty"`
	// Number of comments to the problem.
	CommentCount int32 `json:"commentCount,omitempty"`
	// Tags of entities affected by the problem.
	TagsOfAffectedEntities []TagInfo `json:"tagsOfAffectedEntities,omitempty"`
	// List of events related to the problem.
	RankedEvents []Event `json:"rankedEvents,omitempty"`
	// Provides impact information of the events in an aggregated form. For a more detailed impact analysis, look at 'rankedEvents'
	RankedImpacts []EventRestImpact `json:"rankedImpacts,omitempty"`
	// The number of affected entities per impact level.
	AffectedCounts map[string]interface{} `json:"affectedCounts,omitempty"`
	// The number of entities which were affected, but recovered, per impact level.
	RecoveredCounts map[string]interface{} `json:"recoveredCounts,omitempty"`
	// Whether Dynatrace has found at least one possible root cause for the problem.
	HasRootCause bool `json:"hasRootCause,omitempty"`
}
