/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Synthetic location
type SyntheticLocation struct {
	// Unique id which identifies the location.
	Id string `json:"id"`
	// Location display name.
	Name string `json:"name,omitempty"`
	// Location ip address.
	Ip string `json:"ip"`
	// Location icon URL.
	IconUrl string `json:"iconUrl,omitempty"`
}
