/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Defines the current monitoring state of an entity.
type MonitoringState struct {
	// The current actual monitoring state on the entity.
	ActualMonitoringState string `json:"actualMonitoringState,omitempty"`
	// The monitoring which is expected from the configuration
	ExpectedMonitoringState string `json:"expectedMonitoringState,omitempty"`
	// Defines whether or not the process has to restarted to enable monitoring
	RestartRequired bool `json:"restartRequired,omitempty"`
}
