/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


type ExternalEventOpenNotification struct {
	// Test id.
	TestId string `json:"testId,omitempty"`
	// Unique id which identifies the event.
	EventId string `json:"eventId,omitempty"`
	// Name which will be used to display the event in the UI.
	Name string `json:"name,omitempty"`
	// Event type.
	EventType string `json:"eventType,omitempty"`
	LocationIdsWhereTheEventHappens []string `json:"Location ids where the event happens.,omitempty"`
}
