/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Definition of a custom metric.
type TimeseriesRegistrationMessage struct {
	// The name of the metric that will appear in the user interface. It is limited to 256 characters.
	DisplayName string `json:"displayName,omitempty"`
	// The unit the metric will use. If the parameter is not specified or the wrong value is specified, the `Count` value will be assigned.
	Unit string `json:"unit,omitempty"`
	// Metric dimension key that will be used to report multiple dimensions. For example, a dimension key to report the metric for different network cards for the same firewall. The name of dimensions is only allowed to contain alphanumeric characters, dots ., hyphens -, and underscores _.   The CUSTOM_DEVICE dimension is added to each new custom metric automatically.
	Dimensions []string `json:"dimensions,omitempty"`
	// Technology type definition. Used to group metrics under a logical technology name in the UI.  Metrics must be assigned a software technology type that is identical to the technology type of the custom device you are sending the metric to. For example, if you define your custom device using type `F5-Firewall` you must also register all related custom metrics as type `F5-Firewall`.
	Types []string `json:"types,omitempty"`
}
