/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Contains information of a custom device which should be persisted.
type CustomDevicePushMessage struct {
	// The name of the custom device that will appear in the user interface.
	DisplayName string `json:"displayName,omitempty"`
	// User defined group id of entity. This field is optional but can be considered as required as it leads to a consistent picture of custom device - custom device group topology. If you send a value for this field, the value will be hashed into the Dynatrace custom device id. With that in place, the custom device can only be part of one custom device group without the possibility of flipping. If you don't set the field, we will create the custom device group based on the type, or if the type is not present, based on the custom device id; also the group will not be hashed into the device id which enables the possibility of group flipping for the device. One of many cases where a proper group is important is service detection: you can define which custom devices should lead to the same service by defining the same groupId for those.
	GroupId string `json:"groupId,omitempty"`
	// List of IP addresses that belong to the custom device.   These addresses are used to automatically discover the horizontal communication relationship between this component and all other observed components within Smartscape. Once a connection is discovered, it is automatically mapped and shown within Smartscape.
	IpAddresses []string `json:"ipAddresses,omitempty"`
	// More detailed information about how the custom device accepts communication from other components on the network-port level.   This information is used to automatically connect process-to-process communication relationships with custom components.
	ListenPorts []int32 `json:"listenPorts,omitempty"`
	// Technology type definition of the custom device.   It must be the same technology type of the metric you're reporting.   This overwrites the existing value. Only include this parameter in the request when you want to update it.
	Type string `json:"type,omitempty"`
	// Icon to be displayed for your custom component within Smartscape. Provide the full URL of the icon file.
	Favicon string `json:"favicon,omitempty"`
	// A URL of the configuration web page of the custom device, such as a login page for a firewall or router.
	ConfigUrl string `json:"configUrl,omitempty"`
	// A list of key-value pair properties that will be shown beneath the infographics of your custom device.
	Properties map[string]string `json:"properties,omitempty"`
	// List of custom tags that you want to attach to your custom device.
	Tags []string `json:"tags,omitempty"`
	// List of metric values that are reported for the custom device.   Only include this if you want to report metrics for the custom device.
	Series []EntityTimeseriesData `json:"series,omitempty"`
	// List of host names reltated to the custom device.
	HostNames []string `json:"hostNames,omitempty"`
}
