/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


type ExternalSyntheticTests struct {
	// Synthetic engine name.
	SyntheticEngineName string `json:"syntheticEngineName,omitempty"`
	// Synthetic engine icon URL.
	SyntheticEngineIconUrl string `json:"syntheticEngineIconUrl,omitempty"`
	// Timestamp of when the message was created.
	MessageTimestamp int64 `json:"messageTimestamp"`
	// Test site id definitions and metainfos on test sites.
	Locations []SyntheticLocation `json:"locations,omitempty"`
	// a set of tests
	Tests []ExternalSyntheticTest `json:"tests,omitempty"`
	// Array of one or more synthetic test run results.
	TestResults []ExternalSyntheticTestResult `json:"testResults,omitempty"`
	// Synthetic engine serial.
	SyntheticEngine int32 `json:"syntheticEngine,omitempty"`
}
