/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Describes some external event that was reported as part of a user session
type UserSessionEvents struct {
	// The type of event or error, for errors this is usually 'Error' or 'Crash', for events 'UserTag'
	Type string `json:"type,omitempty"`
	// The name of the event or error
	Name string `json:"name,omitempty"`
	// The DNS domain that was recorded as part of the user action, empty if not applicable
	Domain string `json:"domain,omitempty"`
	// The point in time when the event or error was recorded, in milliseconds since the epoch
	StartTime int64 `json:"startTime,omitempty"`
	// The name of the application, based on the configured detection rules
	Application string `json:"application,omitempty"`
	// The internal id of the application, this is useful when calling various REST APIs, e.g. as key for timeseries queries
	InternalApplicationId string `json:"internalApplicationId,omitempty"`
}
