/*
 * Dynatrace Environment API
 *
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package environment


// Pushes updates on open events to Dynatrace or closes previously open events.
type ExternalSyntheticEvents struct {
	// Synthetic engine name.
	SyntheticEngineName string `json:"syntheticEngineName,omitempty"`
	// Set of open events.
	Open []ExternalEventOpenNotification `json:"open,omitempty"`
	// Set of resolved events.
	Resolved []ExternalEventResolvedNotification `json:"resolved,omitempty"`
}
