/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type CustomService struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// The ID of the custom service.
	Id string `json:"id,omitempty"`
	// The name of the custom service, displayed in the UI.
	Name string `json:"name"`
	// Custom service enabled/disabled.
	Enabled bool `json:"enabled"`
	// The list of rules defining the custom service.
	Rules []DetectionRule `json:"rules"`
	// The queue entry point flag.   Set to `true` for custom messaging services.
	QueueEntryPoint bool `json:"queueEntryPoint"`
	// The list of process groups the custom service should belong to.
	ProcessGroups []string `json:"processGroups,omitempty"`
}
