/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for high CPU saturation detection on ESXi. If not present (null) then default thresholds will be used.
type EsxiHighCpuThresholds struct {
	// Detect high CPU saturation only when CPU usage is higher than N percent in 3 out of 5 samples.
	CpuUsagePercentage int32 `json:"cpuUsagePercentage"`
	// Detect high CPU saturation only when VM CPU ready is higher than N percent in 3 out of 5 samples.
	VmCpuReadyPercentage int32 `json:"vmCpuReadyPercentage"`
	// Detect high CPU saturation only when CPU peak higher than N percent occured in 3 out of 5 samples.
	CpuPeakPercentage int32 `json:"cpuPeakPercentage"`
}
