/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for high network utilization detection. If not present (null) then default thresholds will be used.
type HighNetworkThresholds struct {
	// Detect high network utilization when receive/transmit traffic utilization is higher than N percent in 3 out of 5 samples.
	UtilizationPercentage int32 `json:"utilizationPercentage"`
}
