/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type MethodRule struct {
	// The ID of the method rule.
	Id string `json:"id,omitempty"`
	// The method to instrument.
	MethodName string `json:"methodName"`
	// Fully qualified types of argument the method expects.
	ArgumentTypes []string `json:"argumentTypes"`
	// Fully qualified type the method returns.
	ReturnType string `json:"returnType"`
}
