/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for high write and/or read latency detection on RDS. If not present (null) then default thresholds will be used.
type RdsHighLatencyThresholds struct {
	// Detect high latency when write and/or read latency is higher than N milliseconds in 3 out of 5 samples.
	WriteReadLatency int32 `json:"writeReadLatency"`
}
