/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for overloaded storage detection on physical storage device. If not present (null) then default thresholds will be used.
type OverloadedStorageThresholds struct {
	// Detect overloaded storage when number of command aborts is higher than N in 3 out of 5 samples.
	CommandAbortsNumber int32 `json:"commandAbortsNumber"`
}
