/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for Java out-of-threads detection. If not present (null) then default thresholds will be used.
type OutOfThreadsThresholds struct {
	// Detect Java out of threads when number of out-of-threads exceptions per minute is N or more.
	OutOfThreadsExceptionsNumber int32 `json:"outOfThreadsExceptionsNumber"`
}
