/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type WebApplicationConfig struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// The unique id of the web application, automatically generated by the dynatrace server.
	Identifier string `json:"identifier,omitempty"`
	// The name of the Web Application
	Name string `json:"name"`
	// Real User Monitoring enabled/disabled.
	RealUserMonitoringEnabled bool `json:"realUserMonitoringEnabled"`
	// User session percentage for cost and traffic control (decimal number with three fractional digits).
	CostControlUserSessionPercentage float32 `json:"costControlUserSessionPercentage"`
	// The Key Performance Metric for load actions
	LoadActionKeyPerformanceMetric string `json:"loadActionKeyPerformanceMetric"`
	// The Key Performance Metric for xhr actions
	XhrActionKeyPerformanceMetric string `json:"xhrActionKeyPerformanceMetric"`
	LoadActionApdexSettings Apdex `json:"loadActionApdexSettings"`
	XhrActionApdexSettings Apdex `json:"xhrActionApdexSettings"`
	CustomActionApdexSettings Apdex `json:"customActionApdexSettings"`
	WaterfallSettings WaterfallSettings `json:"waterfallSettings"`
	MonitoringSettings MonitoringSettings `json:"monitoringSettings"`
}
