/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// A condition holds the settings for how to execute matching logic for an entity.
type EntityRuleEngineCondition struct {
	Key EntityRuleEngineConditionKey `json:"key"`
	ComparisonInfo EntityRuleEngineComparisonInfoObjectObject `json:"comparisonInfo"`
}
