/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for high CPU saturation detection. If not present (null) then default thresholds will be used.
type HighCpuSaturationThresholds struct {
	// Detect high CPU saturation when CPU usage is higher than N percent in 3 out of 5 samples.
	CpuSaturation int32 `json:"cpuSaturation"`
}
