/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type DataPrivacy struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// Mask IP addresses and GPS coordinates enabled/disabled.
	MaskIpAddressesAndGpsCoordinates bool `json:"maskIpAddressesAndGpsCoordinates"`
	// Mask user action names (Web applications only) enabled/disabled.
	MaskUserActionNames bool `json:"maskUserActionNames"`
	// Mask personal data in URIs enabled/disabled.
	MaskPersonalDataInUris bool `json:"maskPersonalDataInUris"`
}
