/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Type-specific key to identify the data for which we want to match against.This is an abstract version of the key, in its place use one of the actual implementations for the allowed types: * STRING -> EntityRuleEngineDynamicStringConditionKey * PROCESS_PREDEFINED_METADATA_KEY -> EntityRuleEngineDynamicPgIdCalcInputConditionKey * PROCESS_CUSTOM_METADATA_KEY -> EntityRuleEngineDynamicCustomPgMetadataConditionKey * null (no type is set) -> EntityRuleEngineStaticConditionKey
type EntityRuleEngineConditionKey struct {
	// Defines the attribute used for the filter. Only some are allowed based on the feature it is used for and the specified 'type' outside this condition.
	Attribute string `json:"attribute"`
	Type string `json:"type,omitempty"`
}
