/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type ApplicationDataPrivacy struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// The unique id of the web application
	Identifier string `json:"identifier,omitempty"`
	// Data capture and cookies disabled until JavaScriptAPI dtrum.enable() is called enabled/disabled.
	DataCaptureOptInEnabled bool `json:"dataCaptureOptInEnabled"`
	// Set persistent cookie in order to recognize returning devices enabled/disabled.
	PersistentCookieForUserTracking bool `json:"persistentCookieForUserTracking"`
	// Browsers' \"Do Not Track\" behaviour: IGNORE_DO_NOT_TRACK/CAPTURE_ANONYMIZED/DO_NOT_CAPTURE.
	DoNotTrackBehaviour string `json:"doNotTrackBehaviour"`
}
