/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Configuration of anomaly detection for VMware
type VMwareAnomalyDetectionConfig struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	EsxiHighCpuSaturation EsxiHighCpuSaturationConfig `json:"esxiHighCpuSaturation"`
	EsxiHighMemoryDetection EsxiHighMemoryDetectionConfig `json:"esxiHighMemoryDetection"`
	OverloadedStorageDetection OverloadedStorageDetectionConfig `json:"overloadedStorageDetection"`
	UndersizedStorageDetection UndersizedStorageDetectionConfig `json:"undersizedStorageDetection"`
	SlowPhysicalStorageDetection SlowPhysicalStorageDetectionConfig `json:"slowPhysicalStorageDetection"`
	DroppedPacketsDetection DroppedPacketsDetectionConfig `json:"droppedPacketsDetection"`
	LowDatastoreSpaceDetection LowDatastoreSpaceDetectionConfig `json:"lowDatastoreSpaceDetection"`
}
