/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for high GC activity detection. If not present (null) then default thresholds will be used.
type HighGcActivityThresholds struct {
	// Detect high Garbage Collector activity always when GC time is higher than N percent.
	GcTimePercentage int32 `json:"gcTimePercentage"`
	// Detect high Garbage Collector activity always when GC suspension is higher than N percent in 3 out of 5 samples.
	GcSuspensionPercentage int32 `json:"gcSuspensionPercentage"`
}
