/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type ExtractSubstring struct {
	// The position of the extracted string relative to delimiters.
	Position string `json:"position"`
	// The delimiter string.
	Delimiter string `json:"delimiter"`
	// The end-delimiter string.    Required if the **position** value is `BETWEEN`. Otherwise not allowed.
	EndDelimiter string `json:"endDelimiter,omitempty"`
}
