/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type DiskEventAnomalyDetectionConfig struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// The ID of the disk event.
	Id string `json:"id,omitempty"`
	// The name of the disk event.
	Name string `json:"name"`
	// Whether the disk event is enabled.
	Enabled bool `json:"enabled"`
	// The metric to monitor.
	Metric string `json:"metric"`
	// The event threshold. If the metric is `LowDiskSpace` or `LowInodes`, this is a percentage. For `ReadTimeExceeding` or `WriteTimeExceeding`, milliseconds.
	Threshold float64 `json:"threshold"`
	// The minimum number of violating samples for an event to be triggered. Must not exceed `samples`.
	ViolatingSamples int32 `json:"violatingSamples"`
	// The number of samples that are inspected.
	Samples int32 `json:"samples"`
	DiskNameFilter DiskNameFilterDto `json:"diskNameFilter,omitempty"`
	// Only apply this rule to hosts having these tags.
	TagFilters []TagFilterDto `json:"tagFilters,omitempty"`
}
