/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


// Custom thresholds for low datastore free space detection. If not present (null) then default thresholds will be used.
type LowDatastoreSpaceThresholds struct {
	// Detect low free space when it's lower than N percent.
	FreeSpacePercentage int32 `json:"freeSpacePercentage"`
}
