/*
 * Dynatrace Configuration API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config


type DataSource struct {
	// Data source enbled/disabled.
	Enabled bool `json:"enabled"`
	// The source of the attribute to capture. Works in conjunction with **parameterName** or **methods**.
	Source string `json:"source"`
	ValueProcessing ValueProcessing `json:"valueProcessing,omitempty"`
	// The method specification if the **source** value is `METHOD_PARAM`   Not applicable in other cases.
	Methods []CapturedMethod `json:"methods,omitempty"`
	// The name of the web request parameter to capture.   Required if the **source** is one of the following: `POST_PARAMETER`, `GET_PARAMETER`, `REQUEST_HEADER`, `RESPONSE_HEADER`.   Not applicable in other cases.
	ParameterName string `json:"parameterName,omitempty"`
	Scope ScopeConditions `json:"scope,omitempty"`
	// Specifies the location where the values are captured and stored.   Required if the **source** is one of the following: `GET_PARAMETER`, `URI`, `REQUEST_HEADER`, `RESPONSE_HEADER`.    Not applicable in other cases.    If the **source** value is `REQUEST_HEADER` or `RESPONSE_HEADER`, the `CAPTURE_AND_STORE_ON_BOTH` location is not allowed.
	CapturingAndStorageLocation string `json:"capturingAndStorageLocation,omitempty"`
}
